# Generated by Django 5.0.6 on 2024-07-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shoop', '0003_remove_products_gender_delete_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='products', to='new_shoop.gender'),
        ),
    ]
